### ISSUE TITLE
Unexpected identifier async loadIfNeeded

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [Ty3uK/parcel-plugin-pug#3]
Fresh project and not working... =(

Error:
![img-2018-01-12-14-29-10](https://user-images.githubusercontent.com/10127643/34873768-7f31f4d6-f7a7-11e7-9f4f-8a6c9d537316.png)

`andrew@andrew-ThinkPad-Edge-E545:/var/www/optimum-house$ parcel index.pug
Server running at http://localhost:1234
🚨  Unexpected identifier
  async loadIfNeeded() {
        ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at NativeCompileCache._moduleCompile (/usr/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/usr/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/usr/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/var/www/optimum-house/node_modules/parcel-plugin-pug/build/PugAsset.js:4:15)
    at Module._compile (/usr/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
`

Project tree:
![img-2018-01-12-14-45-15](https://user-images.githubusercontent.com/10127643/34873812-a53e22c6-f7a7-11e7-9051-acaece922a28.png)

Packages:
![img-2018-01-12-14-49-37](https://user-images.githubusercontent.com/10127643/34873946-06e2a394-f7a8-11e7-96f1-2fb1d0cc3252.png)

NodeJS + NPM versions:
![img-2018-01-12-14-51-58](https://user-images.githubusercontent.com/10127643/34873988-3c7a5042-f7a8-11e7-9c05-4e51ef446d8b.png)

**Comment by Ty3uK** [comment]
Yep, big mistake. I'll fix it soon, thanks!

**Comment by Ty3uK** [comment]
Fixed in https://github.com/Ty3uK/parcel-plugin-pug/commit/20e16e67c024443c48c56b92041c2fe8107f25c7. Version 0.2.3 is released. Thanks a lot!

**Comment by Ty3uK** [comment]
Totally fixed in version `0.2.4`

**Comment by Andrew-Dyachenko** [comment]
Cool, now it works!
![2018-01-14 04-59-41](https://user-images.githubusercontent.com/10127643/34912068-d1463e1c-f8e7-11e7-80d4-753e4532cc49.png)
