### ISSUE TITLE
error with parcel 1.5

### ISSUE THREAD

**Issue by njleonzhang** [Ty3uK/parcel-plugin-pug#5]
```
➜  smartlife-yearly-report git:(master) ✗ parcel index.pug
⏳  Building...
Server running at http://localhost:1234
🚨  Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1268:5)
    at new Asset (/Users/leon/Documents/smartCommunity/smartlife-yearly-report/node_modules/parcel-bundler/src/Asset.js:22:30)
    at new PugAsset (/Users/leon/Documents/smartCommunity/smartlife-yearly-report/node_modules/parcel-plugin-pug/build/PugAsset.js:32:9)
    at Parser.getAsset (/Users/leon/.nvm/versions/node/v8.7.0/lib/node_modules/parcel-bundler/src/Parser.js:61:12)
    at Bundler.resolveAsset (/Users/leon/.nvm/versions/node/v8.7.0/lib/node_modules/parcel-bundler/src/Bundler.js:261:29)
    at <anonymous>
```

**Comment by njleonzhang** [comment]
need to build with local parcel 
`node_modules/parcel-bundler/bin/cli.js index.pug`
